version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=consumer
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    networks:
      - consumernet
    volumes:
      - postgres_consumer:/var/lib/postgresql
      - postgres_consumer_data:/var/lib/postgresql/data

networks:
  consumernet:
    driver: bridge

volumes:
  postgres_consumer:
  postgres_consumer_data:

